### ISSUE TITLE
Show total time taken in summary

### ISSUE THREAD

**Issue by JaKXz** [zoubin/tap-summary#1]
First of all, Happy new year (and first issue)! :tada: 

It would be awesome if tap summary showed the total time taken for the tests to run in the summary, because I prefer it to the other tap reporters for all the other information it shows :)

**Comment by zoubin** [comment]
@JaKXz It seems a good idea. I'll work on it. Thanks!

**Comment by zoubin** [comment]
This feature is added in the release 1.2.0.
