### ISSUE TITLE
Hyphenated heading widths are often too wide for terminals

### ISSUE THREAD

**Issue by js-choi** [zoubin/tap-summary#17]
[formatter.js](https://github.com/zoubin/tap-summary/blob/6899e7dc853c20a5ead5f7e430f34897516827ec/lib/formatter.js) has a [`splitter` function](https://github.com/zoubin/tap-summary/blob/6899e7dc853c20a5ead5f7e430f34897516827ec/lib/formatter.js#L157) that adds many hyphens `-----` to either side of the output report’s headings, such as `------------------------------------ Tests ---------------------
-----------------`, `----------------------------------- Summary --------------------
----------------`, and `------------------------------------ Fails ---------------------
----------------`.

[The width of these hyphenated headings is hard-coded at 80.](https://github.com/zoubin/tap-summary/blob/6899e7dc853c20a5ead5f7e430f34897516827ec/lib/formatter.js#L159) However, people, myself included, often write programs in a text-editor window next to a terminal window continuously running unit tests. (Myself, I’m able to work either on a desktop computer, which can fit two 80-unit-wide text-editor windows and a 50-wide terminal window, or a smaller laptop, which can fit one 50-wide text-editor windows and a 50-wide terminal window.) Displays often do not have enough room to fit everything side by side with ≥ 80 text units each, causing unnecessary text wrapping of the long headings.

It would be great if tap-summary would format its headings to take up the [current width of the terminal](https://www.npmjs.com/package/window-size), and no more. Alternatively, it may be simpler to eschew the many hyphens altogether and make the headings simply `# Tests`, `# Summary`, `# Fails`, etc. After all, they’re already prominently colored yellow, and it may make reading reports down along their left sides easier for the eyes.

Thanks for tap-summary!

**Comment by zoubin** [comment]
Good idea! The default formatter in 4.0.0 displays '# Tests'.
