### ISSUE TITLE
Mixed assertions [with AVA] not being counted

### ISSUE THREAD

**Issue by JaKXz** [zoubin/tap-summary#2]
Since AVA is really cool but doesn't have all the assertions that chai does, I find myself mixing assertions in my tests. In my refactoring I am trying to stick to one assertion per test, but we'll ignore the philosophical argument for now.

Is this an AVA issue?

**Comment by zoubin** [comment]
@JaKXz  Could you provide an repro case? I'd like to look into it

**Comment by JaKXz** [comment]
@zoubin here you go: https://gist.github.com/JaKXz/c676f6b5493b0ce90225

~~I think you'll just need to `npm install chai ava` and run `./node_modules/.bin/ava test.js --tap | tap-summary`~~

EDIT: download and run `npm install && npm test`

**Comment by JaKXz** [comment]
@zoubin I took a closer look with the `tap-out` module, and I think it's AVA's TAP output's fault. Thanks for taking some time! :)
