### ISSUE TITLE
Without colors?

### ISSUE THREAD

**Issue by Hypercubed** [zoubin/tap-summary#4]
Would you consider a PR adding a command line switch to disable colors?

**Comment by Hypercubed** [comment]
Hello @zoubin, I created a version of tap-summary that outputs markdown and allows disabling of ANSI.  Please let me know if you are interested in merging these.  If not I can publish as tap-summary-md fork.

https://github.com/Hypercubed/tap-summary/tree/tap-summary-markdown

**Comment by zoubin** [comment]
@Hypercubed Thanks! A PR would be appreciated.
Would you document the usage of no-ansi?

**Comment by Hypercubed** [comment]
Hi @zoubin I'll be glad to submit a PR (or multiple) and document.  I've made three changes in my fork:

1) Disable ANSI using -C flag
2) Disable output during progress using -P flag
3) Output markdown headers (`# Test` instead of `----- Tests ----`).

Do you want all three PRs?

**Comment by Hypercubed** [comment]
Here is what the output looks like: 

With -CP flag to disable ANSI and progress: https://asciinema.org/a/47214
Without flags: https://asciinema.org/a/47215

**Comment by zoubin** [comment]
> 1) Disable ANSI using -C flag
> 2) Disable output during progress using -P flag
> 3) Output markdown headers (# Test instead of ----- Tests ----).

I think 1) and 2) could be merged immediately.
As of 3), perhaps some changes could be made to allow custom formatters. I'll think about it these two days.

**Comment by Hypercubed** [comment]
Well, I was ready to do the PR for `--no-ansi` and `--no-progress` but with the v2.0 refactor looks like I need to rebase.

**Comment by Hypercubed** [comment]
Awesome!!!
